name: 'Omnistrate Image Tag Update Action'
description: 'This action integrates with the Omnistrate CD API'
author: 'Omnistrate'
branding:
  icon: 'activity'
  color: 'blue'

inputs:
  service-id:
    description: 'Service ID'
    required: false
  service-api-id:
    description: 'Service API ID'
    required: false
  product-tier-id:
    description: 'Product Tier ID'
    required: false
  image-config-id:
    description: 'Image Config ID'
    required: false
  tag:
    description: 'Tag'
    required: true
  release-description:
    description: 'Release Description'
    required: false
  username:
    description: 'Username'
    required: true
  password:
    description: 'Password'
    required: true

outputs:
  service-id:
    description: 'The service ID that was updated'
  image-config-id:
    description: 'The image config ID that was updated'
  service-api-id:
    description: 'The service API ID that was updated'
  product-tier-id:
    description: 'The product tier ID that was updated'
  tag:
    description: 'The tag that was updated'
  release-description:
    description: 'The release description that was updated'

runs:
  using: node20
  main: dist/index.js
